name: Self
on:
  pull_request_target:
    types: [opened, edited]
  issues:
    types: [opened, edited]

jobs:
  Self:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        name: Local action
        with:
          pattern: passiflora, cumulonimbus, amorphophallus
          replacement: '`$0`'
          trim-punctuation: true
          token: ${{ secrets.GITHUB_TOKEN }}
